<style>
p	{
	line-height:24px;
}
</style>
<h6>Doctoral Degree - BS to PhD Track</h6>
<p>The Doctoral Program provides students with the interdisciplinary knowledge and skills to conduct independent research in Environmental and Earth Sciences. Dissertation research is the heart of the Doctoral Program, and it is supported carefully selected coursework and development of competency in specific research skills. The BS-PhD Track permits highly qualified students with a Bachelor&lsquo;s degree to complete the PhD without obtaining a Master&lsquo;s degree.</p>
<p>The dissertation is an original and independent research project carried out under the supervision of a faculty member in one of the participating units (Biology, Chemistry, Earth and Environmental Science, Civil and Environmental Engineering, or Urban and Public Affairs). The most important element of success in completing the Doctoral Program is selection of a faculty research advisor and dissertation research topic. Students considering the Doctoral Program should contact faculty members with <a href="http://www.uta.edu/ese/faculty.htm">research interests</a> that match their own interests.</p>
<p>The student&lsquo;s program of coursework is designed in consultation with a faculty advisor and faculty committee to support the student's dissertation research, taking into account their previous background and the need for interdisciplinary training to solve environmental problems. Students in the BS-PhD Track must take 15 hours of <a href="?i=academics&amp;s=graduate&amp;u=core">core courses</a> in Environmental and Earth Sciences. In addition to their primary area of emphasis, the discipline in which dissertation research is conducted, courses are assigned in a secondary area of emphasis to provide interdisciplinary training. Also, by taking courses, passing examinations, or other means, Doctoral students must demonstrate proficiency in a research tool such as statistical data analysis, mathematical modeling, computer programming, or operations research.</p>
<br />