<h6 style="margin-top:0px;">Core Course Offerings for MS &amp; PHD Programs</h6>
<p><strong>CE 5321. Engineering for Environmental Scientists</strong> (3-0). Fundamental principles of engineering science applicable   to the comprehension and design of engineered environmental systems.   Includes water and air quality indices; kinetic and reactor   theory; mass and energy balances; fluid system theory; and applications   of physical, chemical, and biological processes in the design   of engineered environmental systems. May not be used to satisfy any of   the requirements for a graduate degree in Civil Engineering.   Prerequisites: PHYS 1442, CHEM 1302, 1284, MATH 2325.</p>
<p><strong>CE 5319.  Physical-Chemical Processes II</strong> (3-0).    Principles of water chemistry applied to the theory and design of   unit processes including coagulation, precipitation, corrosion,   oxidation-reduction, and membrane processes.  Prerequisite:  CE 3131 and     3334 or consent of instructor.</p>
<p><strong>CE 5328.  Fundamentals of Air Pollution</strong> (3-0).  An   introduction to the air pollution field which encompasses a wide   range of topics, including:  pollutant types, sources, effects; Clean   Air Act; atmosphere and ideal gas law; pollutant measurement; air   pollution meteorology and chemistry; dispersion modeling; air pollution   control; and mobile sources.  Credit not granted for both CE   5328 and 4350.  Prerequisite:  concurrent enrollment in CE 5318 or 5321.</p>
<p><strong>CE 5354. Water Resouces Planning</strong> (3-0). Historical   and current water development concepts. Administrative and allocation   concerns. General principles and procedures of water resource planning   includes regional, multipurpose, economic and systems considerations.   Prerequisite: CE 3301, CE 3309, and IE 3312; or consent of instructor.</p>
<p><strong>CIRP 5341. Environmental Regulations: Laws and Planning</strong> (3-0). Federal, state, and local environmental regulations which have   effect on the practice of city and regional planning. Specific articles,   laws, and directives contrasted and compared to local city design and   development controls. Subjects incluse CERCLA, RCRA, SARA, TSCA, OSH   Act, among others.</p>
<p><strong>CIRP 5342.  Environmental policy</strong> (3-0).  Focuses on the physical environmental dimensions of urbanization including such factors as     pollution, waste disposal, and land use:  stresses the role of economic, social, and political institutions as these affect     environmental quality of the city.  Also offered as URPA 5317; credit will be granted only once.</p>
<p><strong>CIRP 5343.  Foundations of Environmental Policy</strong> (3-0).  Explores how environmental controversy is rooted in   conflict between a number of schools of environmental policy thought   with divergent perspectives on basic issues such as how to cope   with environmental complexity, how to balance the needs of economy and   ecosystem, how to define progress, and what role science should   play in environmental affairs.</p>
<p><strong>CIRP 5352.  Environmental Assessment Policy &amp; Practice</strong> (3-0).  Environmental assessment is the process of determining the   environmental effects of development, facility   construction/modification, and activities that could have a significant   impact on the nation's air, water or land. This course includes review   and analysis of the development of the environmental assessment process   with focus on expectations of how environmental assessment will be   transformed in the era of climate change. Students evaluate new laws and   regulations and the accelerated growth of environmental policy at all   levels of government, especially among urban areas. The course includes   review of selected environmental assessment documents and project case   studies. Central to the course work is understanding the National   Environmental Policy Act (NEPA) which is presented via a detailed study   of the NEPA Process. </p>
<p><strong>EVSE 5309. Environmental Science - Biological Aspects</strong> (3-0). An introduction to the biological components of   environmental systems. Population dynamics, species interactions,   community structure, biodiversity, bioenergetics, nutrient cycling and   human impacts are reviewed. Focus will be on natural processes and their   engineering applications.</p>
<p><strong>EVSE 5310. Environmental Science - Chemical Aspects</strong> (3-0). An introduction to the chemistries of air at different   altitudes, of water systems and of soils. Chemical and physico-chemical   processes at phase boundaries, modeling for kinetics and mass   transport, analytical techniques and disposal and recycling are included   as well as their impact on engineering decisions.</p>
<p> <strong>EVSE 5311.  Environmental Science  - Geological Aspects</strong> (3-0). An introduction to the chemistry of the earth&lsquo;s   surface with special emphasis on natural waters and the biogeochemical   processes controlling water chemistry and element cycling in the   hydrosphere</p>
<p style="text-align:right"><a style='font-size:12px; font-weight:bold;' href='#top'>BACK TO TOP</a></p>